---

- block:
  - name: install pre-reqs for vscode
    apt:
      name:
      - software-properties-common 
      - apt-transport-https
      state: present
      update_cache: true
  - name: add Microsoft repo key
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present
  - name: add Microsoft repo
    apt_repository:
      repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
      filename: microsoft-vscode
      state: present
  - name: install vscode
    apt:
      name: code
      state: present
      update_cache: true

- name: install vscode extensions
  command: code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"
  become: yes
  become_user: "{{ local_username }}"

