---

- block:
  - name: install pre-reqs for az cli
    apt:
      name:
      - software-properties-common 
      - apt-transport-https
      state: present
      update_cache: true
  - name: add Microsoft repo key
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present
  - name: add Microsoft repo
    apt_repository:
      repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli bionic main"
      filename: microsoft-azcli
      state: present
  - name: install azcli
    apt:
      name: azure-cli
      state: present
      update_cache: true

#- block:
#  - name: install pre-reqs for azure data studio
#    apt:
#      name:
#      - libxss1
#      - libgconf-2-4
#      - libunwind8
#      state: present
#      update_cache: true
#  - name: install azure data studio
#    apt:
#      deb: https://go.microsoft.com/fwlink/?linkid=2109254

